# Peer Assignment

## Preliminary stuff
```{r}
library(ggplot2)
```

## Download data script
```{r}
if(!file.exists("../data/activitydata.zip")){
    download.file(url="https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", 
              destfile="../data/activitydata.zip", 
              method="curl")
    unzip(zipfile="../data/activitydata.zip", exdir="../data/", overwrite=TRUE)
}
```

## Impute missing values

``` {r}
rawdata <- read.csv(file="../data/activity.csv")
plotdata <- rawdata
meansteps <- aggregate(steps ~ interval, data=rawdata, FUN=median)
plotdata[is.na(plotdata$steps),]$steps <- meansteps$steps[match(plotdata[is.na(plotdata$steps),]$interval, meansteps$interval)]
```

## Show totals

### Histogram

```{r}
qplot(aggregate(.~ date, plotdata, sum)$steps, binwidth=1000, xlab="total steps per day")
```
### Mean and median

Mean and median are calculated with inline formulas.

__Mean:__ `r mean(aggregate(.~date, plotdata, sum)$steps)` steps

__Median:__ `r median(aggregate(.~date, plotdata, sum)$steps)` steps

## Set up data for activity plotting
```{r}
plotdata$date <- as.Date(plotdata$date)
plotdata$day <- weekdays(plotdata$date)
plotdata$weekpart <- "weekday"
plotdata[ which(plotdata$day == "Saturday" | plotdata$day == "Sunday"), ]$weekpart <- "weekend"
plotdata$weekpart <- as.factor(plotdata$weekpart)
```

## Plot daily activity pattern
```{r fig.width=7, fig.height=6}
qplot(interval, steps, data = plotdata, facets = weekpart ~. ,stat = "summary", fun.y = "mean", geom = "line")
```